name: Build and Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.platform.os }}-${{ matrix.platform.arch }}
    runs-on: ${{ matrix.platform.os-type }}
    strategy:
      matrix:
        platform:
          - os: linux
            os-type: ubuntu-latest
            arch: x86_64
          - os: darwin
            os-type: macos-latest
            arch: x86_64
          - os: linux
            os-type: ubuntu-latest
            arch: aarch64
          - os: darwin
            os-type: macos-latest
            arch: aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'

      - name: Install cross-compilation tools
        run: |
          if [ "${{ matrix.platform.os }}" = "linux" ]; then
            if [ "${{ matrix.platform.arch }}" = "aarch64" ]; then
              sudo apt-get update
              sudo apt-get install -y gcc-aarch64-linux-gnu
            fi
          fi

      - name: Build release binary
        env:
          GOOS: ${{ matrix.platform.os == 'darwin' && 'darwin' || 'linux' }}
          GOARCH: ${{ matrix.platform.arch == 'x86_64' && 'amd64' || 'arm64' }}
          CGO_ENABLED: 0
          CC: ${{ matrix.platform.arch == 'aarch64' && matrix.platform.os == 'linux' && 'aarch64-linux-gnu-gcc' || '' }}
        run: |
          go build -ldflags="-w -s" -o lit ./cmd/lit

      - name: Prepare binary
        shell: bash
        run: |
          BINARY_NAME="lit-${{ matrix.platform.os }}-${{ matrix.platform.arch }}"
          cp lit "${BINARY_NAME}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lit-${{ matrix.platform.os }}-${{ matrix.platform.arch }}
          path: lit*
          retention-days: 1

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          find artifacts -name "lit*" -type f -exec cp {} release-assets/ \;
          ls -la release-assets/

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: release-assets/*
          fail_on_unmatched_files: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}